### ISSUE TITLE
关于波形播放指定位置

### ISSUE THREAD

**Issue by MinchinWang** [CarGuo/RecordWave#12]
我录完了一段10秒的录音，然后我想在3秒的时候开始播放，并且波形也要有相应的效果，请问如何设置。

**Comment by CarGuo** [comment]
目前没做这样的支持，如果需要这样的功能，你可以在库里修改，在播放波形的绘制线程里，在三秒之后再给数据。

**Comment by CarGuo** [comment]
fix by v1.1.1
