### ISSUE TITLE
有大神帮忙解决获取音频时长问题么?  万分感谢

### ISSUE THREAD

**Issue by lh414035210** [CarGuo/RecordWave#22]
在项目中,做了一个语音评论, 在adapter中利用media获取音频时长,  首次进入界面时,加载语音评论很卡! 是不是要另开一个线程获取音频时长啊?   有大神帮忙解决下么

**Comment by CarGuo** [comment]
获取时长你可以异步啊。这种模式，推荐你用rxjava2

**Comment by lh414035210** [comment]
![nma gb 53 4 hgz nd u](https://user-images.githubusercontent.com/24253339/28023347-48e72b36-65c0-11e7-87f0-d437bbe9ae69.png)
![Uploading 65OI95AOEGI9%PS%YU$)STF.png…]()

**Comment by lh414035210** [comment]
![nma gb 53 4 hgz nd u](https://user-images.githubusercontent.com/24253339/28023425-750e1b5c-65c0-11e7-84bc-9af71cbd3716.png)
![65oi95aoegi9 ps yu stf](https://user-images.githubusercontent.com/24253339/28023433-7d4f9228-65c0-11e7-9c6c-c304f7dda4cf.png) 
同步的可以获得time,异步的并不能获得time
