### ISSUE TITLE
如果频繁点击播放会出现问题

### ISSUE THREAD

**Issue by Wade-Cai** [CarGuo/RecordWave#29]
MediaPlayer﹕ internal/external state mismatch corrected 

查了下说是MediaPlayer.isPlaying()这个方法频繁调用导致的，建议用个变量标记。。

另外还有回调太频繁导致的问题： The application may be doing too much work on its main thread.

我觉得将AudioPlayer中的Timer的period加大一些可能会比较好

**Comment by CarGuo** [comment]
频繁点击播放，其实···可以最简单的对频繁点击处理下，做一些点击频率限制。
