### ISSUE TITLE
调用录音直接异常

### ISSUE THREAD

**Issue by sorgs** [CarGuo/RecordWave#30]
10-31 14:27:07.743 30059-30240/com.sevegame.voicerecorder W/System.err: java.util.ConcurrentModificationException
10-31 14:27:07.743 30059-30240/com.sevegame.voicerecorder W/System.err:     at java.util.ArrayList.writeObject(ArrayList.java:738)
10-31 14:27:07.743 30059-30240/com.sevegame.voicerecorder W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
10-31 14:27:07.744 30059-30240/com.sevegame.voicerecorder W/System.err:     at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:977)
10-31 14:27:07.744 30059-30240/com.sevegame.voicerecorder W/System.err:     at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1536)
10-31 14:27:07.744 30059-30240/com.sevegame.voicerecorder W/System.err:     at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1472)
10-31 14:27:07.744 30059-30240/com.sevegame.voicerecorder W/System.err:     at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1218)
10-31 14:27:07.744 30059-30240/com.sevegame.voicerecorder W/System.err:     at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:346)
10-31 14:27:07.744 30059-30240/com.sevegame.voicerecorder W/System.err:     at com.shuyu.waveview.AudioWaveView.deepCopy(AudioWaveView.java:285)
10-31 14:27:07.744 30059-30240/com.sevegame.voicerecorder W/System.err:     at com.shuyu.waveview.AudioWaveView$drawThread.run(AudioWaveView.java:201)

**Comment by CarGuo** [comment]
demo复现？

**Comment by sorgs** [comment]
我是多么想运行你的demo啊，Android studio3.0打开下的demo，各种报错，直接就运行不了

**Comment by sorgs** [comment]
大佬，把调用方法写出来也行啊。真心懵逼了一上午了

**Comment by CarGuo** [comment]
我这边3.0打开没有问题呀，你gradle使用2.2.2就好了

**Comment by sorgs** [comment]
强制改为2.2.2之后
Error:The versions of the Android Gradle plugin and Gradle are not compatible.
Please do one of the following:<ul><li>Update your plugin to version 2.4. This will require changes to build.gradle due to API changes.
<a href='https://goo.gl/sEn5eA'>Open migration guide</a></li><li>Downgrade Gradle to version 3.5.
<a href="fixGradleVersionInWrapper">Fix Gradle wrapper and re-import project</a></li></ul>

**Comment by CarGuo** [comment]
原本就是2.2.2，应该你打开的时候，点了update的按钮，根路径的gradle/wrapper下的properties文件里应该是xxxxx2.14.1-all.zip

**Comment by sorgs** [comment]
那现在有什么办法哇
