### ISSUE TITLE
沒有波形畫面

### ISSUE THREAD

**Issue by tenSunFree** [CarGuo/RecordWave#32]
請問一下, 我直接在新的項目的XML裡面 使用AudioWaveView這個控件
並且建立一個Button, 來執行resolveRecord() 這個方法

執行之後, 我發現 在本機上找的到剛剛產生的錄音檔, 而且有聲音
但是AudioWaveView控件 在錄製過程中, 始終顯示不出波形的畫面, 是不是我忽略了什麼細節?

**Comment by CarGuo** [comment]
请参考demo或者在demo复现
