### ISSUE TITLE
波形闪烁问题

### ISSUE THREAD

**Issue by Leongeneral** [CarGuo/RecordWave#34]
我用了你这个绘制波形的原理，用了两个bitmap，但是还是会偶现闪烁问题

**Comment by CarGuo** [comment]
有时候确实会有这样的情况，可以试试用textureview

**Comment by Leongeneral** [comment]
textureview绘制背景不能绘制成透明色有解决办法吗？

**Comment by CarGuo** [comment]
这个没办法，透明不了的
