### ISSUE TITLE
录音、播放正常，但录音波形不显示

### ISSUE THREAD

**Issue by zj2050** [CarGuo/RecordWave#35]
开发环境 as

**Comment by CarGuo** [comment]
参考demo吧，如果demo没问题我也很难协助…

**Comment by zj2050** [comment]
@CarGuo 你如果方便可以试一下放在popwindow里面，无论用waveview 本地编译 还是导入，都不行， demo确实没问题，不知道这个是不是bug，或者其他冲突异常？
谢谢

**Comment by CarGuo** [comment]
已更新demo

**Comment by zj2050** [comment]
@CarGuo 谢谢更新，问题我们也找到了， 是你这个控件和腾讯的直播接口冲突了，你这个波形不显示，腾讯的直播接口直接初始化就死机了， 停用你这个腾讯的可以了，停用腾讯的你这个也可以了， 不知道怎么解决， 如果方便你可以看一下

**Comment by CarGuo** [comment]
和腾讯直播冲突？？？除了mp3转码或者录音焦点之外想不出其他的-

**Comment by zj2050** [comment]
@CarGuo 对，就是直接库导入，不使用都不行， 可能是你说的问题，因为我们测了另外一个只mp3录制的也不行：https://github.com/hss01248/AndroidMP3Recorder
是否可以方便调试一下？

**Comment by CarGuo** [comment]
你可以看下livesdk包含哪些库和so

**Comment by zj2050** [comment]
@CarGuo ilivesdk包含
![jietu20180117-161050](https://user-images.githubusercontent.com/4464947/35032213-0bf48c60-fba1-11e7-971c-12dac3c6dbb7.png)
这是用到的库，你参考一下

**Comment by zj2050** [comment]
@CarGuo 还请烦心给协助一下，如果能解决冲突，你这个对我们帮助太大了，录音这个功能我们就可以直接引入项目，谢谢

**Comment by CarGuo** [comment]
没看出来

**Comment by zj2050** [comment]
@CarGuo 你方便导入一下那个ilivesdk和做一个初始化跟踪一下吗？

**Comment by CarGuo** [comment]
很遗憾的告诉你，我这样的demo中引入后也是正常的····
不过我建议你，加上ndk过滤，貌似腾讯直播的so有一些是没有的，不设置指定so目录会有问题的
```
 defaultConfig {
        ····
        ndk {
            //设置支持的SO库架构
            abiFilters 'armeabi-v7a'
        }
    }

```

**Comment by zj2050** [comment]
@CarGuo 你真是最热心的作者，可惜只能点一颗星，谢谢，加上abi 和 v7过滤可以了
