### ISSUE TITLE
Android 加载 SO 库 UnsatisfiedLinkError 错误

### ISSUE THREAD

**Issue by yangchong211** [CarGuo/RecordWave#37]
错误日志定位到这句话：System.loadLibrary("mp3lame");
在华为mate8上安装就会出现加载so库导致崩溃，报的错误是：UnsatisfiedLinkError 
然后换了手机偶尔出现该bug，有时候不出现。看了你的源码并且百度搜索了该错误，但还是没有解决……
求大神支招！！！

**Comment by CarGuo** [comment]
尝试加上ndk过滤
```
 defaultConfig {
        ····
        ndk {
            //设置支持的SO库架构
            abiFilters 'armeabi-v7a'
        }
    }

```

**Comment by yangchong211** [comment]
这样貌似还是难以解决实际问题，我在网上看到ReLinker解决方案，而且还说了加载本地so库的危险性。只是不知道那个库中解决办法是：加入Relink库到工程中，使用ReLinker.loadLibrary(context, "mylibrary")代替System.loadLibrary("mylibrary");
如果用在阁下那个LameUtil方法中，这个context上下文怎么获取呢？
关于文章链接：https://www.csdn.net/article/2015-11-10/2826182-the-perils-of-loading-native-libraries-on-android
感谢大神……

**Comment by CarGuo** [comment]
不是很理解你说的，你可以试试demo

**Comment by yangchong211** [comment]
好的，非常感谢你！
