### ISSUE TITLE
支持播放wav格式的音频吗

### ISSUE THREAD

**Issue by AwinHe** [CarGuo/RecordWave#38]
支持播放wav格式的音频吗， 我播放wav的音频就crash了

**Comment by AwinHe** [comment]
http://192.168.1.160:8088/audios/2018/2/23/4d3f902d-d2c0-4840-8305-13dc18780153.wav

**Comment by CarGuo** [comment]
不好意思，一忙起来都忘记了，项目目前只解码mp3
