### ISSUE TITLE
Wave view not working in Fragment when onPause Called

### ISSUE THREAD

**Issue by cisankit** [CarGuo/RecordWave#4]
It does not display waves when recording started after onPause.
Please help!

**Comment by CarGuo** [comment]
ok！i will try to fix it！

**Comment by cisankit** [comment]
Thanks :+1:  waiting for the solution.

**Comment by CarGuo** [comment]
sorry,I change demo to fragment , and recording started after onPause, but it do well?  did you stopView onPause?you can try on the new demo.  
try , change demo  ```resolveStopRecord``` to  ```resolveRecord``` after onPause.
