### ISSUE TITLE
github上新版本无法使用

### ISSUE THREAD

**Issue by nickylee11** [CarGuo/RecordWave#40]
compile 'com.github.CarGuo:RecordWave:v1.1.8'无效，1.1.4及其以下才有效

**Comment by CarGuo** [comment]
compile 'com.github.CarGuo:RecordWave:v1.1.8' 测试可以正常依赖，在demo中也可以正常使用

![5a9de5f1e4b0dde7e237c366](https://user-images.githubusercontent.com/10770362/37008094-85684182-211b-11e8-9407-a2eb55aaa549.jpg)

**Comment by nickylee11** [comment]
嗯，是的，今天可以正常依赖了。多谢！
