### ISSUE TITLE
明明有权限，录制的时候会提示没有麦克风权限

### ISSUE THREAD

**Issue by nickylee11** [CarGuo/RecordWave#42]
demo中也有这个问题，有录制权限，toast 提示“没有麦克风权限”。代码如下：
mRecorder.setErrorHandler(new Handler() {
            @Override
            public void handleMessage(Message msg) {
                super.handleMessage(msg);
                if (msg.what == MP3Recorder.ERROR_TYPE) {
                    Toast.makeText(getActivity(), "没有麦克风权限", Toast.LENGTH_SHORT).show();
                    resolveError();
                }
            }
        });

**Comment by CarGuo** [comment]
你可以断点跟踪源码，这是内部获取麦克风有问题，可以看看输入
