### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by fff4** [CarGuo/RecordWave#43]
我申请权限的的时候，先拒绝权限，然后第二次在申请，这个mRecorder.start();就会出问题，直接被try。

**Comment by fff4** [comment]
try的原因是权限被拒

**Comment by CarGuo** [comment]
是的，因为低版本没有请求录音权限的方法，所以 setErrorHandler通知你错误

**Comment by fff4** [comment]
那我应该怎么解决呢？现在是，除非一次性申请录音和读写权限通过，不然就会使用不了，this.mFileOutputStream = new FileOutputStream(file);直接提示权限被拒

**Comment by CarGuo** [comment]
每次点击录制前，先判断权限然后申请申请···

**Comment by fff4** [comment]
我现在就是这么做的，在录制之前，我先申请权限才给录制。我的问题是，当我在申请权限的时候，用户先拒绝一次，然后在重新给我允许权限，这个时候我使用这个录音框架，然后就会一直报权限被拒。

**Comment by fff4** [comment]
不好意思  是我这边的问题  申请了权限组的权限后就没问题了，之前是单个的权限申请
