### ISSUE TITLE
AudioWaveView先设置暂停，再调用stopView(true)，无法清空波形图

### ISSUE THREAD

**Issue by MagnifierSun** [CarGuo/RecordWave#44]
`/**
     * 停止绘制
     */
    public void stopView(boolean cleanView) {
        mPause = false;
        mIsDraw = false;
        if (mInnerThread != null) {
            while (mInnerThread.isAlive()) ;
        }
        if (cleanView) {
            mRecDataList.clear();
            mBackCanVans.drawColor(Color.TRANSPARENT, PorterDuff.Mode.CLEAR);
            mCanvas.drawColor(Color.TRANSPARENT, PorterDuff.Mode.CLEAR);
        }
    }`

试了很久，发现要加mPause = false这个才能全部清空，问题原因我也不懂

**Comment by CarGuo** [comment]
清空只要把list里的数据都清了就可以
