### ISSUE TITLE
LameUtil.init报错

### ISSUE THREAD

**Issue by zhupengxiang** [CarGuo/RecordWave#45]
No implementation found for void com.llkj.testrecord.mp3recorder.util.LameUtil.init(int, int, int, int, int) (tried Java_com_llkj_testrecord_mp3recorder_
我直接把recordwave的代码全部考进项目里报错，但是直接gradle引用就没问题 试了好几遍了 我想知道是哪的问题

**Comment by CarGuo** [comment]
native 的so 会认包名的

**Comment by zhupengxiang** [comment]
你的意思是我只能gradle引用么

**Comment by CarGuo** [comment]
不是，如果你需要用到这个so，so的内部的jni结构是通过 _packagename_init_类似这样的方法的，所以你的LameUtil.init等 lame模块必须创建一个一模一样的包名，放到里面去到能用 native 的方式调用到

**Comment by zhupengxiang** [comment]
你是修改过么 因为我以前直接用MP3recrder的源码是没问题的

**Comment by zhupengxiang** [comment]
还有你刚刚上面说的我没大看懂  我直接把LameUtil放到我项目包名同级下面么

**Comment by CarGuo** [comment]
这个你看看jni开发的大致实现逻辑吧

**Comment by zhupengxiang** [comment]
好吧  谢谢了 那我还是gradle引用吧
