### ISSUE TITLE
Can we play audio by buffering from a web url

### ISSUE THREAD

**Issue by cisankit** [CarGuo/RecordWave#5]
Hello, Can we play an mp3 from web by passing the url in audiowaveview.
Help!

**Comment by CarGuo** [comment]
Hello, I don't understand this demand. if you only play mp3, try use MediaPlayer

**Comment by cisankit** [comment]
My question is, If the music player work with waveview if I pass a web url of audio file instead of file path from phone. like following : 
    audioPlayer.playUrl("http://searchgurbani.com/audio/sggs/1.mp3");
        resolvePlayUI();
It will work or not.
Thanks in advance :+1:  :)

**Comment by CarGuo** [comment]
It can work with web url。😁

**Comment by cisankit** [comment]
I've tried with the above. can you please suggest what I need to change

**Comment by CarGuo** [comment]
sorry，It can play by web Url，but not supprot buffter now
