### ISSUE TITLE
Help solve the problem (没有麦克风权限)

### ISSUE THREAD

**Issue by b1f5fb3a7a7e9c5d2c4f2e6b5** [CarGuo/RecordWave#7]
< File AndroidManifest.xml >
https://github.com/b1f5fb3a7a7e9c5d2c4f2e6b5/noname/blob/master/AndroidManifest.xml

< File *.java >
https://github.com/b1f5fb3a7a7e9c5d2c4f2e6b5/noname/blob/master/MyMorseToText.java

The program fulfills an error:

         mRecorder.setErrorHandler(new Handler() {
            @Override
            public void handleMessage(Message msg) {
                super.handleMessage(msg);
                if (msg.what == MP3Recorder.ERROR_TYPE) {
                  Toast.makeText(mHome, "没有麦克风权限", Toast.LENGTH_SHORT).show(); // <<< !!!
                    resolveError();
                }
            }
        });

Could you explain what I'm doing wrong?

----------------------------------------
PS: I'm new, so do not judge strictly.

**Comment by CarGuo** [comment]
Looks like you banned recording authority . Find your application in your phone authority management .
