### ISSUE TITLE
Unable to retrieve AudioTrack pointer for write()

### ISSUE THREAD

**Issue by cisankit** [CarGuo/RecordWave#8]
Shows this exception while we play another audio by stopping the current audio..:

W/System.err: java.lang.IllegalStateException: Unable to retrieve AudioTrack pointer for write()
W/System.err:     at android.media.AudioTrack.native_write_byte(Native Method)
W/System.err:     at android.media.AudioTrack.write(AudioTrack.java:1255)at com.piterwilson.audio.MP3RadioStreamPlayer.decodeLoop(MP3RadioStreamPlayer.java:376)
at com.piterwilson.audio.MP3RadioStreamPlayer.access$300(MP3RadioStreamPlayer.java:30)
at com.piterwilson.audio.MP3RadioStreamPlayer$DecodeOperation.doInBackground(MP3RadioStreamPlayer.java:486)
 W/System.err:     at com.piterwilson.audio.MP3RadioStreamPlayer$DecodeOperation.doInBackground(MP3RadioStreamPlayer.java:482)
 W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:292)
 W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by cisankit** [comment]
Okk
will wait for the response.

**Comment by CarGuo** [comment]
I try fix it by v1.0.9，it case by audioTrack stop , but write still.

**Comment by cisankit** [comment]
Thanks
